/** Major areas / neighbourhoods in Dhaka city (shared with team location assignments). */
export const DHAKA_AREAS = [
  "Gulshan",
  "Banani",
  "Baridhara",
  "Dhanmondi",
  "Mirpur",
  "Uttara",
  "Motijheel",
  "Old Dhaka",
  "Mohammadpur",
  "Bashundhara",
  "Tejgaon",
  "Farmgate",
  "Wari",
  "Lalbagh",
  "Rampura",
  "Badda",
  "Khilgaon",
  "Jatrabari",
  "Shyamoli",
  "Kallyanpur",
  "Green Road",
  "Elephant Road",
  "Malibagh",
  "Azimpur",
  "Niketon",
  "Cantonment",
  "Pallabi",
  "Kafrul",
  "Keraniganj",
  "Other",
];

export const TEAM_LOCATION_AREAS = DHAKA_AREAS.filter((area) => area !== "Other");
